### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ykapare** [awslabs/awsprocesscreds#32]
While doing git clone using command line getting the following issue:

Traceback (most recent call last):
  File "C:\Users\ykapare\AppData\Local\Programs\Python\Python36\Scripts\git-remote-codecommit-script.py", line 11, in <module>
    load_entry_point('git-remote-codecommit==0.5', 'console_scripts', 'git-remote-codecommit')()
  File "c:\users\ykapare\appdata\local\programs\python\python36\lib\site-packages\git_remote_codecommit\__init__.py", line 152, in main
    context = Context.from_url(remote_url)
  File "c:\users\ykapare\appdata\local\programs\python\python36\lib\site-packages\git_remote_codecommit\__init__.py", line 125, in from_url
    credentials = session.get_credentials()
  File "C:\Users\ykapare\AppData\Roaming\Python\Python36\site-packages\botocore\session.py", line 425, in get_credentials
    'credential_provider').load_credentials()
  File "C:\Users\ykapare\AppData\Roaming\Python\Python36\site-packages\botocore\credentials.py", line 1693, in load_credentials
    creds = provider.load()
  File "C:\Users\ykapare\AppData\Roaming\Python\Python36\site-packages\botocore\credentials.py", line 789, in load
    creds_dict = self._retrieve_credentials_using(credential_process)
  File "C:\Users\ykapare\AppData\Roaming\Python\Python36\site-packages\botocore\credentials.py", line 815, in _retrieve_credentials_using
    parsed = botocore.compat.json.loads(stdout.decode('utf-8'))
  File "c:\users\ykapare\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\ykapare\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\ykapare\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ismashal** [comment]
It is prompting the password but once enters the password showing the same error
